export function createRosdepYaml(packagesContent: string, rosdistro: string) {
  const packages = packagesContent
    .split("\n")
    .filter((line) => line.startsWith("Package: "))
    .map((line) => line.split(" ")[1]);

  const rosdepDict = packages.map((pkg) => {
    const pkgKey = pkg.startsWith(`ros-${rosdistro}-`)
      ? pkg.replace(`ros-${rosdistro}-`, "").replaceAll("-", "_")
      : pkg;
    return [pkgKey, pkg];
  });

  return `# Auto generated by fortefibre-apt-repo
${rosdepDict.map(([key, value]) => `${key}:\n  ubuntu: ${value}`).join("\n")}

# EOF
`;
}
